/*
 * This source file was generated by the Gradle 'init' task
 */
package com.joger.bookfetcher

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertTrue

class AppTest {
    @Test
    fun sampleTest() {
        // Basic placeholder test to ensure compilation passes
        assertTrue(true)
    }
}
