/*
 * This source file was generated by the Gradle 'init' task
 */
package com.joger.bookfetcher

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.options.option
import java.util.concurrent.TimeUnit
import kotlinx.serialization.*
import kotlinx.serialization.json.*
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.Response
import okhttp3.Protocol
import java.io.File
import java.io.FileOutputStream

@Serializable
data class Author(
    val name: String
)

@Serializable
data class Book(
    val id: Int,
    val title: String,
    val authors: List<Author> = emptyList(),
    // Formats maps MIME types to download links
    val formats: Map<String, String> = emptyMap()
)

@Serializable
data class GutendexResponse(
    // Access the results array directly via this property
    val results: List<Book>
)

val jsonParser = Json {
    ignoreUnknownKeys = true
}

fun getBooks(author: String?, title: String?, language: String?): GutendexResponse {
    val client = OkHttpClient.Builder()
        .protocols(listOf(Protocol.HTTP_1_1))
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    val request = Request.Builder()
        .url("https://gutendex.com/books?search=$author%20$title&languages=$language")
        .build()

    client.newCall(request).execute().use { response ->
        val body = response.body?.string() ?: ""
        val book = jsonParser.decodeFromString<GutendexResponse>(body)
        return book
    }
}

fun downloadBook(book: Book, destinationFile: File) {
    val client = OkHttpClient.Builder()
        .protocols(listOf(Protocol.HTTP_1_1))
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    val request = Request.Builder()
        .url(book.formats["application/epub+zip"] ?: "")
        .build()

    client.newCall(request).execute().use { response ->
        if (!response.isSuccessful) {
            error("Download failed with HTTP code: ${response.code}")
        }

        val body = response.body ?: error("Empty response body")

        // Stream binary data directly to the local file
        body.byteStream().use { inputStream ->
            FileOutputStream(destinationFile).use { outputStream ->
                inputStream.copyTo(outputStream)
            }
        }
    }
}

class Fetcher : CliktCommand() {
    val bookTitle: String? by option()
    val bookAuthor: String? by option()
    val bookLanguage: String? by option()

    override fun run() {
        if (bookTitle.isNullOrBlank() && bookAuthor.isNullOrBlank()) {
            echo("Error: Please provide at least --book-title or --book-author.")
            return
        }

        println("bookTitle: $bookTitle, bookAuthor: $bookAuthor, bookLanguage: $bookLanguage")
        val book = getBooks(bookAuthor, bookTitle, bookLanguage)

    }
}

fun main(args: Array<String>) {
    Fetcher().main(args)
}
